name: Make web version using emscripten

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".gitignore"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake git build-essential python3

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v15

      - name: Build Project
        run: |
          mkdir build
          cd build/
          emcmake cmake -B build-web/ -DCMAKE_BUILD_TYPE=Release && cmake --build build-web

      - name: Upload artefact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "build-web/"

      - name: Deploy artefact to GitHub Pages
        uses: actions/deploy-pages@v4
